//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicDbService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClassicalMusicEntities : DbContext
    {
        public ClassicalMusicEntities()
            : base("name=ClassicalMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Catalog> Catalogs { get; set; }
        public virtual DbSet<CatalogNumber> CatalogNumbers { get; set; }
        public virtual DbSet<Composer> Composers { get; set; }
        public virtual DbSet<ComposerBiography> ComposerBiographies { get; set; }
        public virtual DbSet<ComposerImage> ComposerImages { get; set; }
        public virtual DbSet<ComposerShortBiography> ComposerShortBiographies { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<CompositionCollection> CompositionCollections { get; set; }
        public virtual DbSet<Era> Eras { get; set; }
        public virtual DbSet<Instrumentation> Instrumentations { get; set; }
        public virtual DbSet<Key> Keys { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Movement> Movements { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<Recording> Recordings { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
    }
}
