//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicDbService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Composition()
        {
            this.Movements = new HashSet<Movement>();
            this.CatalogNumbers = new HashSet<CatalogNumber>();
            this.Composers = new HashSet<Composer>();
            this.Links = new HashSet<Link>();
            this.Recordings = new HashSet<Recording>();
        }
    
        public int CompositionId { get; set; }
        public string Name { get; set; }
        public string Dates { get; set; }
        public string Nickname { get; set; }
        public string Premiere { get; set; }
        public string Dedication { get; set; }
        public string Occasion { get; set; }
        public bool IsPopular { get; set; }
        public string Comment { get; set; }
        public Nullable<int> KeyId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> InstrumentationId { get; set; }
        public Nullable<int> CompositionCollectionId { get; set; }
    
        public virtual Key Key { get; set; }
        public virtual CompositionCollection CompositionCollection { get; set; }
        public virtual Instrumentation Instrumentation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogNumber> CatalogNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composer> Composers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recording> Recordings { get; set; }
    }
}
